export class UserDetails {
    
    constructor(data:string | any){
        this.userGroup = data.userGroup;
        this.description = data.description;
        this.accountNatureAdd = data.accountNatureAdd;
        this.accountNatureDelete = data.accountNatureDelete;
        this.accountNatureInquiry = data.accountNatureInquiry;
        this.accountNatureUpdate = data.accountNatureUpdate;
        this.ccraReport = data.ccraReport;
        this.creditCheck = data.creditCheck;
        this.creditInfoAdd = data.creditInfoAdd;
        this.creditInfoDelete = data.creditInfoDelete;
        this.creditInfoInquiry = data.creditInfoInquiry;
        this.creditInfoUpdate = data.creditInfoUpdate;
        this.creditInfoDownloadRequestBIU = data.creditInfoDownloadRequestBIU;
        this.creditInfoDownloadRequestCRM = data.creditInfoDownloadRequestCRM;
        this.creditInfoDownloadRequestMort = data.creditInfoDownloadRequestMort;
        this.accountTypeAdd = data.accountTypeAdd;
        this.accountTypeDelete = data.accountTypeDelete;
        this.accountTypeInquiry = data.accountTypeInquiry;
        this.accountTypeUpdate = data.accountTypeUpdate;
        this.pcbInfoInquiry = data.pcbInfoInquiry;
        this.ruleAdd = data.ruleAdd;
        this.ruleDelete = data.ruleAdd;
        this.ruleInquiry = data.ruleAdd;
        this.ruleUpdate = data.ruleAdd;
        this.tuHost2HostAdd = data.tuHost2HostAdd;
        this.tuHost2HostInquiry = data.tuHost2HostInquiry;
        this.tuHost2HostUpdate = data.tuHost2HostUpdate;
        this.tuCCLCardAdd = data.tuCCLCardAdd;
        this.tuCCLCardUpdate = data.tuCCLCardUpdate;
        this.tuSCBCardAdd = data.tuSCBCardAdd;
        this.tuSCBCardUpdate = data.tuSCBCardUpdate;
        this.smeAccountTypeAdd = data.smeAccountTypeAdd;
        this.smeAccountTypeDelete = data.smeAccountTypeAdd;
        this.smeAccountTypeInquiry = data.smeAccountTypeInquiry;
        this.smeAccountTypeUpdate = data.smeAccountTypeUpdate
        this.scoreMapAdd = data.scoreMapAdd;
        this.scoreMapDelete = data.scoreMapDelete;
        this.scoreMapInquiry = data.scoreMapInquiry;
        this.scoreMapUpdate = data.scoreMapUpdate;
        this.s83clcorpAdd = data.s83clcorpAdd;
        this.s83clcorpDelete = data.s83clcorpDelete;
        this.s83clcorpInquiry = data.s83clcorpInquiry;
        this.s83clcorpUpdate = data.s83clcorpUpdate;
        this.s83CLAdd = data.s83CLAdd;
        this.s83CLDelete = data.s83CLDelete;
        this.s83CLInquiry = data.s83CLInquiry;
        this.s83CLUpdate = data.s83CLUpdate;
        this.s83clparamAdd = data.s83clparamAdd;
        this.s83clparamDelete = data.s83clparamDelete;
        this.s83clparamInquiry = data.s83clparamInquiry;
        this.s83clparamUpdate = data.s83clparamUpdate;
        this.s85HRAdd = data.s85HRAdd;
        this.s85HRDelete = data.s85HRDelete;
        this.s85HRInquiry = data.s85HRInquiry;
        this.s85HRUpdate = data.s85HRUpdate;
        this.mcraDataContribution = data.mcraDataContribution;
        this.mcraverification = data.mcraverification;
    }
    userGroup: string;
    description: string;
    accountNatureAdd: boolean;
    accountNatureDelete: boolean;
    accountNatureInquiry: boolean;
    accountNatureUpdate: boolean;
    ccraReport: boolean;
    creditCheck: boolean;
    creditInfoAdd: boolean;
    creditInfoDelete: boolean;
    creditInfoInquiry: boolean;
    creditInfoUpdate: boolean;
    creditInfoDownloadRequestBIU: boolean;
    creditInfoDownloadRequestCRM: boolean;
    creditInfoDownloadRequestMort: boolean;
    accountTypeAdd: boolean;
    accountTypeDelete: boolean;
    accountTypeInquiry: boolean;
    accountTypeUpdate: boolean;
    pcbInfoInquiry: boolean;
    ruleAdd: boolean;
    ruleDelete: boolean;
    ruleInquiry: boolean;
    ruleUpdate: boolean;
    tuHost2HostAdd: boolean;
    tuHost2HostInquiry: boolean;
    tuHost2HostUpdate: boolean;
    tuCCLCardAdd: boolean;
    tuCCLCardUpdate: boolean;
    tuSCBCardAdd: boolean;
    tuSCBCardUpdate: boolean;
    smeAccountTypeAdd: boolean;
    smeAccountTypeDelete: boolean;
    smeAccountTypeInquiry: boolean;
    smeAccountTypeUpdate: boolean;
    scoreMapAdd: boolean;
    scoreMapDelete: boolean;
    scoreMapInquiry: boolean;
    scoreMapUpdate: boolean;
    s83clcorpAdd: boolean;
    s83clcorpDelete: boolean;
    s83clcorpInquiry: boolean;
    s83clcorpUpdate: boolean;
    s83CLAdd: boolean;
    s83CLDelete: boolean;
    s83CLInquiry: boolean;
    s83CLUpdate: boolean;
    s83clparamAdd: boolean;
    s83clparamDelete: boolean;
    s83clparamInquiry: boolean;
    s83clparamUpdate: boolean;
    s85HRAdd: boolean;
    s85HRDelete: boolean;
    s85HRInquiry: boolean;
    s85HRUpdate: boolean;
    mcraDataContribution: boolean;
    mcraverification: boolean;
}